/**
 * MIT License - 2021
 */
package claudiosoft.commons;

/**
 * A convenient Java exception to identify errors generated by JarBox
 */
public class CTException extends Exception {

    public CTException(Exception ex) {
        super(ex.getMessage(), ex);
    }

    public CTException(String errorMessage) {
        super(errorMessage);
    }

    public CTException(String errorMessage, Throwable ex) {
        super(errorMessage, ex);
    }
}
