/**
 * MIT License - 2021
 */
package claudiosoft.utils;

/**
 * A convenient Java exception to identify errors generated by JarBox
 */
public class MinException extends Exception {

    public MinException(String errorMessage) {
        super(errorMessage);
    }

    public MinException(String errorMessage, Throwable ex) {
        super(errorMessage, ex);
    }
}
